// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMTnXhpjT_WYjSzh2kF1B78i7SiPOivRA',
    appId: '1:995866417662:web:54ebfd6769e3e7038148af',
    messagingSenderId: '995866417662',
    projectId: 'solway-inventory',
    authDomain: 'solway-inventory.firebaseapp.com',
    storageBucket: 'solway-inventory.appspot.com',
    measurementId: 'G-PRR1DEDX8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDni75FLTHKrDLfMfBW1_K_xn9XER60lbk',
    appId: '1:995866417662:android:4582d185098f8d448148af',
    messagingSenderId: '995866417662',
    projectId: 'solway-inventory',
    storageBucket: 'solway-inventory.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtDAq06FpCSP4ku4BnG0SUwOYg2kbj6Do',
    appId: '1:995866417662:ios:e2472e9e589e7f3f8148af',
    messagingSenderId: '995866417662',
    projectId: 'solway-inventory',
    storageBucket: 'solway-inventory.appspot.com',
    iosClientId: '995866417662-8f7gj7cs1f11m9cdjv16s43srq6m4icp.apps.googleusercontent.com',
    iosBundleId: 'com.solway.invetory',
  );
}
